

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { LeftContainer } from "@/components/LeftContainer/LeftContainer";
import { Header } from "@/components/Header";
import { LoginSectionProvider } from "@/context/loginSectionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} center min-h-screen`}>

        <LoginSectionProvider>
          {children}
        </LoginSectionProvider>

      </body>
    </html>
  );
}
